// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.696
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func HomePage(stats []StatValues) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container mx-auto p-8 mt-8\"><!-- Create Room Form --><div class=\"mb-12\"><h2 class=\"text-3xl font-bold mb-6\">Create a New Room</h2><form action=\"/room\" method=\"POST\" class=\"grid grid-cols-1 md:grid-cols-3 gap-4\"><input type=\"text\" id=\"roomName\" name=\"roomName\" placeholder=\"Enter room name\" class=\"px-5 py-3 border rounded-md text-lg\" required> <label class=\"form-control w-full max-w-xs\"><div class=\"label\"><span class=\"label-text\">Choose a vote type</span></div><select class=\"select select-primary w-full max-w-xs\" name=\"voteType\" required><option disabled>Vote type:</option> <option>Fibonacci</option> <option>True/False</option></select></label><div class=\"md:col-span-2\"><button type=\"submit\" class=\"bg-blue-600 text-white px-6 py-3 rounded-md w-full md:w-auto\">Create Room</button></div></form></div><div id=\"result\"></div><!-- Join Room Form --><div><h2 class=\"text-3xl font-bold mb-6\">Join an Existing Room</h2><form action=\"/room/join\" method=\"POST\" class=\"grid grid-cols-1 md:grid-cols-4 gap-4\"><input type=\"text\" id=\"displayName\" name=\"displayName\" placeholder=\"Enter display name\" class=\"px-5 py-3 border rounded-md text-lg\" required> <input type=\"text\" id=\"roomID\" name=\"roomID\" placeholder=\"Enter room ID\" class=\"px-5 py-3 border rounded-md text-lg\" required><div class=\"md:col-span-2\"><button type=\"submit\" class=\"bg-green-600 text-white px-6 py-3 rounded-md w-full md:w-auto\">Join Room</button></div></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Stats(stats).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
